version: '3.0'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: tictactoe_backend
    ports:
      - "8080:8080"
    environment:
      - USER_POOL_ID=${REACT_APP_USER_POOL_ID}

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: tictactoe_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_IP=${REACT_APP_BACKEND_IP}
      - REACT_APP_USER_POOL_ID=${REACT_APP_USER_POOL_ID}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}